version: "3"
services:
  postgres:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  postgres-for-tests:
    image: postgres:14
    volumes:
      - ./data/pg_data_for_tests:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
  postgres-for-tests-unsafe:
    image: postgres:14
    volumes:
      - type: tmpfs
        target: /dbdata
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /dbdata
      POSTGRES_DB: upp-test
    command: postgres -c fsync=off -c full_page_writes=off -c shared_buffers=1024 -c max_connections=1000
  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  minio:
    image: minio/minio
    command: server /data
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: FAKEKEY
      MINIO_SECRET_KEY: FAKESECRET
volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
  surrealdb_data:
    driver: local
